version: '3.8'

services:
  frontend-app:
    image: 192.168.235.132:8082/docker-releases2/react-frontend:latest
    container_name: frontend-app
    ports:
      - "5173:80" # 5173 pour l'hôte, 80 pour le conteneur (Nginx)
    networks:
      - kaddem-network
    restart: unless-stopped

networks:
  kaddem-network:
    external: true
